[package]
name = "ogscluner"
version = "2.0.1"
edition = "2021"

[dependencies]
async-std = "1.12.0"
serde = "1.0.204"
ciborium = "0.2.2"
regex = "1.10.6"
poise = "0.6.1"
rand = "0.8.5"
shuttle-runtime = "0.48.0"
shuttle-serenity = "0.48.0"