[package]
name = "ogscluner"
version = "1.0.0"
edition = "2021"

[dependencies]
serde = "1.0.204"
serde_cbor = "0.11.2"
serenity = "0.12.2"
rand = "0.8.5"
shuttle-runtime = "0.47.0"
shuttle-serenity = "0.47.0"