[package]
name = "ogscluner"
version = "3.0.0"
edition = "2021"

[dependencies]
async-std = "1.12.0"
bitflags =  "2.9.1"
serde = "1.0.204"
ciborium = "0.2.2"
regex = "1.10.6"
poise = "0.6.1"
rand = "0.9.0"
shuttle-runtime = "0.52.0"
shuttle-serenity = "0.52.0"